name: lbzsunalarm
description: "sunset alarm"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  suntime: ^0.1.0
  lat_lng_to_timezone: ^0.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: false